[project]
name = "data-engineer-exercise"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-autofix>=0.13.1",
    "dbt-core>=1.10.13",
    "dbt-duckdb>=1.9.6",
    "duckdb>=1.4.1",
]
